### ISSUE TITLE
Out of memory error with GMP timelock puzzles

### ISSUE THREAD

**Issue by Rjected** [mit-dci/opencx#14]
**Describe the bug**
When running the fred daemon, solving many timelock puzzles in one long auction makes GMP crash. 

**To Reproduce**
1. In `~/.opencx/fred/fred.conf`, set `auctiontime=30000000000`
2. `go build ./cmd/fred/...`
3. `go build ./cmd/ocx/...`
4. `./fred -vvv` in one terminal
5. `./ocx placeauctionorder buy regtest/litereg 10000 10`
6. Repeat the previous step 4 times

**Expected behavior**
I expected the puzzles to be solved without running out of memory

```
dan@dan-pc ~/D/P/opencx> ./fred -vvv
passphrase: 

2019/05/15 13:50:57.953518 [DEBUG] Asset 0: regtest
2019/05/15 13:50:57.953562 [DEBUG] Asset 1: vtcreg
2019/05/15 13:50:57.953570 [DEBUG] Asset 2: litereg
2019/05/15 13:50:57.953598 [DEBUG] Pair 0: regtest_vtcreg
2019/05/15 13:50:57.953605 [DEBUG] Pair 1: regtest_litereg
2019/05/15 13:50:57.953614 [DEBUG] Pair 2: vtcreg_litereg
2019/05/15 13:50:58.101533 [INFO] Starting an auction with auction time 30000000000
2019/05/15 13:50:58.101678 [INFO] Starting Auction Clock!
2019/05/15 13:50:58.101711 [INFO] Auction clock tick!
2019/05/15 13:50:58.101735 [INFO] Waiting for tick
2019/05/15 13:50:58.101776 [INFO] Notifying signals
2019/05/15 13:50:58.101895 [INFO]  === will start to listen on noise-rpc ===
2019/05/15 13:50:58.101927 [INFO] Registering RPC API over Noise protocol ...
2019/05/15 13:50:58.102075 [INFO] Starting RPC Server over noise protocol
2019/05/15 13:50:58.102514 [INFO] Running RPC-Noise server on [::]:12345
2019/05/15 13:51:06.954237 [INFO] Received timelocked order!
2019/05/15 13:51:06.954503 [INFO] Got a new puzzle for auction f32e6f018a64bcd1108f9affd472b2afbec8b9e2707965a8e7da76eccbb3ec29
2019/05/15 13:51:08.076423 [INFO] Received timelocked order!
2019/05/15 13:51:08.076590 [INFO] Got a new puzzle for auction f32e6f018a64bcd1108f9affd472b2afbec8b9e2707965a8e7da76eccbb3ec29
2019/05/15 13:51:09.312454 [INFO] Received timelocked order!
2019/05/15 13:51:09.312779 [INFO] Got a new puzzle for auction f32e6f018a64bcd1108f9affd472b2afbec8b9e2707965a8e7da76eccbb3ec29
2019/05/15 13:51:10.556470 [INFO] Received timelocked order!
2019/05/15 13:51:10.556654 [INFO] Got a new puzzle for auction f32e6f018a64bcd1108f9affd472b2afbec8b9e2707965a8e7da76eccbb3ec29
GNU MP: Cannot reallocate memory (old_size=8 new_size=3750000040)
SIGABRT: abort
PC=0x7fab88d5982f m=12 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7fab88d5982f
stack: frame={sp:0x7fab6d739b00, fp:0x0} stack=[0x7fab6cf3a288,0x7fab6d739e88)
00007fab6d739a00:  0000000000000000  0000000000000000 
00007fab6d739a10:  0000000000000000  0000000000000000 
00007fab6d739a20:  0000000000647178 <github.com/ncw/gmp.(*Int).doinit.func1+56>  000000380019dfc8 
00007fab6d739a30:  0000000000000000  0000000000000000 
00007fab6d739a40:  0000000000000000  00007fab6d739b00 
00007fab6d739a50:  0000000000451c43 <runtime.tracebackdefers+83>  0000000000000000 
00007fab6d739a60:  0000000000000000  0000000000000000 
00007fab6d739a70:  0000000000e869a0  0000000000000000 
00007fab6d739a80:  0000000000e869a0  0000000000bd6a58 
00007fab6d739a90:  0000000000bd6a58  0000000000000000 
00007fab6d739aa0:  0000000000000000  0000000000000000 
00007fab6d739ab0:  0000000000000000  0000000000000000 
00007fab6d739ac0:  0000000000000000  0000000000000000 
00007fab6d739ad0:  0000000000bd6a58  0000000000e869a0 
00007fab6d739ae0:  000000000045e7b1 <runtime.goexit+1>  000000000045e7b1 <runtime.goexit+1> 
00007fab6d739af0:  0000000000000000  000000c00005efd0 
00007fab6d739b00: <0000000000000000  000000c00005efd0 
00007fab6d739b10:  000000c00005efd8  0000000000000000 
00007fab6d739b20:  0000000000000000  00007fab6d739ce0 
00007fab6d739b30:  0000000000449cc6 <runtime.copystack+630>  00007fab50000020 
00007fab6d739b40:  0000000000001000  00007fab50000020 
00007fab6d739b50:  0000000000001000  00007fab88ee1aa0 
00007fab6d739b60:  00000000df868000  00000000df8475b0 
00007fab6d739b70:  0000000001de7270  000000000001ed90 
00007fab6d739b80:  fffffffe7fffffff  ffffffffffffffff 
00007fab6d739b90:  ffffffffffffffff  ffffffffffffffff 
00007fab6d739ba0:  ffffffffffffffff  ffffffffffffffff 
00007fab6d739bb0:  ffffffffffffffff  ffffffffffffffff 
00007fab6d739bc0:  ffffffffffffffff  ffffffffffffffff 
00007fab6d739bd0:  ffffffffffffffff  ffffffffffffffff 
00007fab6d739be0:  ffffffffffffffff  ffffffffffffffff 
00007fab6d739bf0:  ffffffffffffffff  ffffffffffffffff 
runtime: unknown pc 0x7fab88d5982f
stack: frame={sp:0x7fab6d739b00, fp:0x0} stack=[0x7fab6cf3a288,0x7fab6d739e88)
00007fab6d739a00:  0000000000000000  0000000000000000 
00007fab6d739a10:  0000000000000000  0000000000000000 
00007fab6d739a20:  0000000000647178 <github.com/ncw/gmp.(*Int).doinit.func1+56>  000000380019dfc8 
00007fab6d739a30:  0000000000000000  0000000000000000 
00007fab6d739a40:  0000000000000000  00007fab6d739b00 
00007fab6d739a50:  0000000000451c43 <runtime.tracebackdefers+83>  0000000000000000 
00007fab6d739a60:  0000000000000000  0000000000000000 
00007fab6d739a70:  0000000000e869a0  0000000000000000 
00007fab6d739a80:  0000000000e869a0  0000000000bd6a58 
00007fab6d739a90:  0000000000bd6a58  0000000000000000 
00007fab6d739aa0:  0000000000000000  0000000000000000 
00007fab6d739ab0:  0000000000000000  0000000000000000 
00007fab6d739ac0:  0000000000000000  0000000000000000 
00007fab6d739ad0:  0000000000bd6a58  0000000000e869a0 
00007fab6d739ae0:  000000000045e7b1 <runtime.goexit+1>  000000000045e7b1 <runtime.goexit+1> 
00007fab6d739af0:  0000000000000000  000000c00005efd0 
00007fab6d739b00: <0000000000000000  000000c00005efd0 
00007fab6d739b10:  000000c00005efd8  0000000000000000 
00007fab6d739b20:  0000000000000000  00007fab6d739ce0 
00007fab6d739b30:  0000000000449cc6 <runtime.copystack+630>  00007fab50000020 
00007fab6d739b40:  0000000000001000  00007fab50000020 
00007fab6d739b50:  0000000000001000  00007fab88ee1aa0 
00007fab6d739b60:  00000000df868000  00000000df8475b0 
00007fab6d739b70:  0000000001de7270  000000000001ed90 
00007fab6d739b80:  fffffffe7fffffff  ffffffffffffffff 
00007fab6d739b90:  ffffffffffffffff  ffffffffffffffff 
00007fab6d739ba0:  ffffffffffffffff  ffffffffffffffff 
00007fab6d739bb0:  ffffffffffffffff  ffffffffffffffff 
00007fab6d739bc0:  ffffffffffffffff  ffffffffffffffff 
00007fab6d739bd0:  ffffffffffffffff  ffffffffffffffff 
00007fab6d739be0:  ffffffffffffffff  ffffffffffffffff 
00007fab6d739bf0:  ffffffffffffffff  ffffffffffffffff 

goroutine 27 [syscall]:
runtime.cgocall(0x869d80, 0xc00005ec98, 0xc0000a5bc0)
        /usr/lib/go/src/runtime/cgocall.go:128 +0x5b fp=0xc00005ec68 sp=0xc00005ec30 pc=0x4098db
github.com/ncw/gmp._Cfunc_mpz_pow_ui(0xc0000a5b80, 0xc0000a5bc0, 0x6fc23ac00)
        _cgo_gotypes.go:1095 +0x45 fp=0xc00005ec98 sp=0xc00005ec68 pc=0x642615
github.com/ncw/gmp.(*Int).Exp.func1(0xc0000a5b80, 0xc0000a5bc0, 0xc0000a5a00)
        /home/dan/go/pkg/mod/github.com/ncw/gmp@v1.0.4/int.go:713 +0x175 fp=0xc00005ece8 sp=0xc00005ec98 pc=0x64acb5
github.com/ncw/gmp.(*Int).Exp(0xc0000a5b80, 0xc0000a5bc0, 0xc0000a5a00, 0x0, 0xc0000a5a80)
        /home/dan/go/pkg/mod/github.com/ncw/gmp@v1.0.4/int.go:713 +0x9a fp=0xc00005ed18 sp=0xc00005ece8 pc=0x64575a
github.com/mit-dci/opencx/crypto/rsw.(*PuzzleRSW).SolveGMPCkXOR(0xc0000a5480, 0x0, 0x0, 0x0, 0x203000, 0x203000)
        /home/dan/Documents/Projects/opencx/crypto/rsw/rswtimelock.go:220 +0x493 fp=0xc00005edc8 sp=0xc00005ed18 pc=0x650ce3
github.com/mit-dci/opencx/crypto/rsw.(*PuzzleRSW).Solve(0xc0000a5480, 0x0, 0x0, 0xc0000ffec0, 0x411f79, 0xc0000a58e0)
        /home/dan/Documents/Projects/opencx/crypto/rsw/rswtimelock.go:210 +0x2b fp=0xc00005ee08 sp=0xc00005edc8 pc=0x65080b
github.com/mit-dci/opencx/crypto/timelockencoders.SolvePuzzleRC5(0xc0001d2000, 0xb1, 0xb1, 0xb462e0, 0xc0000a5480, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/dan/Documents/Projects/opencx/crypto/timelockencoders/blockciphers.go:112 +0x52 fp=0xc00005ef00 sp=0xc00005ee08 pc=0x6c4a22
github.com/mit-dci/opencx/match.SolveRC5AuctionOrderAsync(0xc0001d0000, 0xc000078720)
        /home/dan/Documents/Projects/opencx/match/auctionorder.go:30 +0x94 fp=0xc00005efd0 sp=0xc00005ef00 pc=0x6c5ae4
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc00005efd8 sp=0xc00005efd0 pc=0x45e7b1
created by github.com/mit-dci/opencx/cxauctionserver.(*OpencxAuctionServer).PlacePuzzledOrder
        /home/dan/Documents/Projects/opencx/cxauctionserver/orders.go:27 +0x21f

goroutine 1 [chan receive]:
main.main()
        /home/dan/Documents/Projects/opencx/cmd/fred/fred.go:188 +0x5a9

goroutine 19 [syscall]:
os/signal.signal_recv(0x0)
        /usr/lib/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
        /usr/lib/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/lib/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 70 [syscall]:
github.com/ncw/gmp._Cfunc_mpz_pow_ui(0xc0004a7c40, 0xc0004a7c60, 0x6fc23ac00)
        _cgo_gotypes.go:1095 +0x45
github.com/ncw/gmp.(*Int).Exp.func1(0xc0004a7c40, 0xc0004a7c60, 0xc0004a7b80)
        /home/dan/go/pkg/mod/github.com/ncw/gmp@v1.0.4/int.go:713 +0x175
github.com/ncw/gmp.(*Int).Exp(0xc0004a7c40, 0xc0004a7c60, 0xc0004a7b80, 0x0, 0xc0004a7bc0)
        /home/dan/go/pkg/mod/github.com/ncw/gmp@v1.0.4/int.go:713 +0x9a
github.com/mit-dci/opencx/crypto/rsw.(*PuzzleRSW).SolveGMPCkXOR(0xc0004a7a40, 0x0, 0x0, 0x0, 0x203000, 0x203000)
        /home/dan/Documents/Projects/opencx/crypto/rsw/rswtimelock.go:220 +0x493
github.com/mit-dci/opencx/crypto/rsw.(*PuzzleRSW).Solve(0xc0004a7a40, 0xc000464f6c, 0x2, 0xc000464ec0, 0x411f79, 0xc0004a7ae0)
        /home/dan/Documents/Projects/opencx/crypto/rsw/rswtimelock.go:210 +0x2b
github.com/mit-dci/opencx/crypto/timelockencoders.SolvePuzzleRC5(0xc0004b00c0, 0xb1, 0xb1, 0xb462e0, 0xc0004a7a40, 0xc000464f68, 0x2, 0x0, 0x1, 0x0)
        /home/dan/Documents/Projects/opencx/crypto/timelockencoders/blockciphers.go:112 +0x52
github.com/mit-dci/opencx/match.SolveRC5AuctionOrderAsync(0xc0000b6370, 0xc000078720)
        /home/dan/Documents/Projects/opencx/match/auctionorder.go:30 +0x94
created by github.com/mit-dci/opencx/cxauctionserver.(*OpencxAuctionServer).PlacePuzzledOrder
        /home/dan/Documents/Projects/opencx/cxauctionserver/orders.go:27 +0x21f

goroutine 10 [select]:
database/sql.(*DB).connectionOpener(0xc0004bc240, 0xb4ade0, 0xc00048c500)
        /usr/lib/go/src/database/sql/sql.go:1000 +0xe8
created by database/sql.OpenDB
        /usr/lib/go/src/database/sql/sql.go:670 +0x15e

goroutine 11 [select]:
database/sql.(*DB).connectionResetter(0xc0004bc240, 0xb4ade0, 0xc00048c500)
        /usr/lib/go/src/database/sql/sql.go:1013 +0xfb
created by database/sql.OpenDB
        /usr/lib/go/src/database/sql/sql.go:671 +0x194

goroutine 12 [select]:
github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher.func1(0xc000078600, 0xc0004bc300, 0xc0004d4300)
        /home/dan/go/pkg/mod/github.com/go-sql-driver/mysql@v1.4.1/connection_go18.go:178 +0xbf
created by github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher
        /home/dan/go/pkg/mod/github.com/go-sql-driver/mysql@v1.4.1/connection_go18.go:175 +0xbe

goroutine 14 [chan receive]:
github.com/mit-dci/opencx/cxauctionserver.(*OpencxAuctionServer).AuctionOrderHandler(0xc0004b22d0, 0xc000078720)
        /home/dan/Documents/Projects/opencx/cxauctionserver/handlers.go:11 +0x42
created by github.com/mit-dci/opencx/cxauctionserver.InitServer
        /home/dan/Documents/Projects/opencx/cxauctionserver/auctionserver.go:41 +0x2a4

goroutine 15 [chan receive]:
github.com/mit-dci/opencx/cxauctionserver.(*OpencxAuctionServer).AuctionClock(0xc0004b22d0)
        /home/dan/Documents/Projects/opencx/cxauctionserver/clock.go:33 +0xb5
created by github.com/mit-dci/opencx/cxauctionserver.InitServer
        /home/dan/Documents/Projects/opencx/cxauctionserver/auctionserver.go:44 +0x2c6

goroutine 16 [chan receive]:
main.main.func1(0xc0003e01a0)
        /home/dan/Documents/Projects/opencx/cmd/fred/fred.go:163 +0x167
created by main.main
        /home/dan/Documents/Projects/opencx/cmd/fred/fred.go:156 +0x476

goroutine 50 [chan receive]:
github.com/mit-dci/opencx/cxauctionrpc.OffButtonCloseListener(0xc0003e01a0, 0xb49ae0, 0xc000493440)
        /home/dan/Documents/Projects/opencx/cxauctionrpc/listener.go:91 +0x3c
github.com/mit-dci/opencx/cxauctionrpc.NoiseListenAsync(0xc0000ee0e0, 0xc000493260, 0xc0003e01a0, 0x9746ab, 0x9, 0xc0004b3039)
        /home/dan/Documents/Projects/opencx/cxauctionrpc/listener.go:47 +0x2bb
created by main.main
        /home/dan/Documents/Projects/opencx/cmd/fred/fred.go:186 +0x592

goroutine 51 [IO wait]:
internal/poll.runtime_pollWait(0x7fab84292310, 0x72, 0x0)
        /usr/lib/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc00046a498, 0x72, 0x0, 0x0, 0x9728cf)
        /usr/lib/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
        /usr/lib/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc00046a480, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go/src/internal/poll/fd_unix.go:384 +0x1ba
net.(*netFD).accept(0xc00046a480, 0xc0004d4360, 0x7fab88cdfd98, 0x0)
        /usr/lib/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc0000100c8, 0xc000119f28, 0xc000119f30, 0x30)
        /usr/lib/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc0000100c8, 0xc000119f68, 0x2, 0x0, 0x1)
        /usr/lib/go/src/net/tcpsock.go:260 +0x48
github.com/mit-dci/opencx/cxnoise.(*Listener).listen(0xc000493440)
        /home/dan/Documents/Projects/opencx/cxnoise/listener.go:82 +0xc9
created by github.com/mit-dci/opencx/cxnoise.NewListener
        /home/dan/Documents/Projects/opencx/cxnoise/listener.go:64 +0x200

goroutine 52 [select]:
github.com/mit-dci/opencx/cxnoise.(*Listener).Accept(0xc000493440, 0xaba6c0, 0xc0004b2370, 0x7fab6efc2088, 0xc00048cb80)
        /home/dan/Documents/Projects/opencx/cxnoise/listener.go:207 +0xbb
net/rpc.(*Server).Accept(0xc0004b2370, 0xb49ae0, 0xc000493440)
        /usr/lib/go/src/net/rpc/server.go:632 +0x69
created by github.com/mit-dci/opencx/cxauctionrpc.NoiseListenAsync
        /home/dan/Documents/Projects/opencx/cxauctionrpc/listener.go:46 +0x294

goroutine 46 [syscall]:
github.com/ncw/gmp._Cfunc_mpz_powm(0xc0004a78a0, 0xc0004a77c0, 0xc0004a78c0, 0xc0004a7840)
        _cgo_gotypes.go:1110 +0x45
github.com/ncw/gmp.(*Int).Exp.func2(0xc0004a78a0, 0xc0004a77c0, 0xc0004a78c0, 0xc0004a7840)
        /home/dan/go/pkg/mod/github.com/ncw/gmp@v1.0.4/int.go:716 +0x285
github.com/ncw/gmp.(*Int).Exp(0xc0004a78a0, 0xc0004a77c0, 0xc0004a78c0, 0xc0004a7840, 0xc0004a78c0)
        /home/dan/go/pkg/mod/github.com/ncw/gmp@v1.0.4/int.go:716 +0xe3
github.com/mit-dci/opencx/crypto/rsw.(*PuzzleRSW).SolveGMPCkXOR(0xc0004a7380, 0x7fab88cdfd98, 0x0, 0x8, 0x203000, 0x203000)
        /home/dan/Documents/Projects/opencx/crypto/rsw/rswtimelock.go:220 +0x4c2
github.com/mit-dci/opencx/crypto/rsw.(*PuzzleRSW).Solve(0xc0004a7380, 0x10, 0x917e60, 0xc00004d6c0, 0x411f79, 0xc0004a7760)
        /home/dan/Documents/Projects/opencx/crypto/rsw/rswtimelock.go:210 +0x2b
github.com/mit-dci/opencx/crypto/timelockencoders.SolvePuzzleRC5(0xc00015c000, 0xb1, 0xb1, 0xb462e0, 0xc0004a7380, 0x412808, 0x30, 0x93cd60, 0xc0000bc301, 0xc00009cd20)
        /home/dan/Documents/Projects/opencx/crypto/timelockencoders/blockciphers.go:112 +0x52
github.com/mit-dci/opencx/match.SolveRC5AuctionOrderAsync(0xc0000b62d0, 0xc000078720)
        /home/dan/Documents/Projects/opencx/match/auctionorder.go:30 +0x94
created by github.com/mit-dci/opencx/cxauctionserver.(*OpencxAuctionServer).PlacePuzzledOrder
        /home/dan/Documents/Projects/opencx/cxauctionserver/orders.go:27 +0x21f

goroutine 48 [syscall]:
github.com/ncw/gmp._Cfunc_mpz_powm(0xc0004a65c0, 0xc0004a64e0, 0xc0004a65e0, 0xc0004a6560)
        _cgo_gotypes.go:1110 +0x45
github.com/ncw/gmp.(*Int).Exp.func2(0xc0004a65c0, 0xc0004a64e0, 0xc0004a65e0, 0xc0004a6560)
        /home/dan/go/pkg/mod/github.com/ncw/gmp@v1.0.4/int.go:716 +0x285
github.com/ncw/gmp.(*Int).Exp(0xc0004a65c0, 0xc0004a64e0, 0xc0004a65e0, 0xc0004a6560, 0xc0004a65e0)
        /home/dan/go/pkg/mod/github.com/ncw/gmp@v1.0.4/int.go:716 +0xe3
github.com/mit-dci/opencx/crypto/rsw.(*PuzzleRSW).SolveGMPCkXOR(0xc00000ece0, 0x0, 0x0, 0x0, 0x203000, 0x203000)
        /home/dan/Documents/Projects/opencx/crypto/rsw/rswtimelock.go:220 +0x4c2
github.com/mit-dci/opencx/crypto/rsw.(*PuzzleRSW).Solve(0xc00000ece0, 0x0, 0x0, 0xc0001036c0, 0x411f79, 0xc0004a6480)
        /home/dan/Documents/Projects/opencx/crypto/rsw/rswtimelock.go:210 +0x2b
github.com/mit-dci/opencx/crypto/timelockencoders.SolvePuzzleRC5(0xc00015c0c0, 0xb1, 0xb1, 0xb462e0, 0xc00000ece0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/dan/Documents/Projects/opencx/crypto/timelockencoders/blockciphers.go:112 +0x52
github.com/mit-dci/opencx/match.SolveRC5AuctionOrderAsync(0xc0004b2140, 0xc000078720)
        /home/dan/Documents/Projects/opencx/match/auctionorder.go:30 +0x94
created by github.com/mit-dci/opencx/cxauctionserver.(*OpencxAuctionServer).PlacePuzzledOrder
        /home/dan/Documents/Projects/opencx/cxauctionserver/orders.go:27 +0x21f

rax    0x0
rbx    0x6
rcx    0x7fab88d5982f
rdx    0x0
rdi    0x2
rsi    0x7fab6d739b00
rbp    0x8
rsp    0x7fab6d739b00
r8     0x0
r9     0x7fab6d739b00
r10    0x8
r11    0x246
r12    0x0
r13    0x1
r14    0x7fab50000c30
r15    0x200
rip    0x7fab88d5982f
rflags 0x246
cs     0x33
fs     0x0
gs     0x0

```

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version 5.0.13-arch1-1-ARCH

**Additional context**
This might be a bug in `ncw/gmp`.

**Comment by Rjected** [comment]
Update: not a bug
